---
title: "Evolution de la COVID19"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}

library(flexdashboard)
library(readxl)
library(readr)
library(ggplot2)
library(animation)
library(gganimate)
library(leaflet)
library(leaflet.minicharts)
library(dplyr)
library(tidyverse)
library(dygraphs)
library(plotly)
library(directlabels)
library(lubridate)
library(magrittr)

# Chargement de la base de données
base_coviz<-read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/web-data/data/cases_country.csv")
base1<-base_coviz[which(base_coviz$Country_Region=="Benin" & base_coviz$Confirmed>0),]
indic1<-base1$Confirmed
indic2<-base1$Deaths
indic3<-base1$Recovered
indic4<-base1$Active

# these computing functions are only toy examples
CasConfirmes = function(...) return(indic1)
CasDecedes = function(...) return(indic2)
casGueris = function(...) return(indic3)
casTraitement = function(...) return(indic4)


base_coviz_downl<-read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/web-data/data/cases_time.csv")
base_coviz_downl$new_lat<-base_coviz$Lat[match(base_coviz_downl$Country_Region,base_coviz$Country_Region)]
base_coviz_downl$new_long<-base_coviz$Long_[match(base_coviz_downl$Country_Region,base_coviz$Country_Region)]
base2<-base_coviz_downl[which(base_coviz_downl$Country_Region=="Benin" & base_coviz_downl$Confirmed>0),]

base_coviz_downl$date<-rev(time_length(interval(start = ymd(base_coviz_downl$Report_Date_String), end = today()), unit = "days"))
base_coviz_downl$mois<-month(base_coviz_downl$Report_Date_String )
base_coviz_downl$jour<-mday(base_coviz_downl$Report_Date_String )
base_coviz_downl$absc<-base_coviz_downl$mois + (base_coviz_downl$jour)/32
base_pays_lim<-base_coviz_downl[which(base_coviz_downl$Country_Region=="Benin" | base_coviz_downl$Country_Region=="Togo" | base_coviz_downl$Country_Region=="Burkina Faso" | base_coviz_downl$Country_Region=="Niger" ),]

accumulate_by <- function(dat, var) {
  var <- lazyeval::f_eval(var, dat)
  lvls <- plotly:::getLevels(var)
  dats <- lapply(seq_along(lvls), function(x) {
    cbind(dat[var %in% lvls[seq(1, x)], ], frame = lvls[[x]])
  })
  dplyr::bind_rows(dats)
}



 #colors
confirmed_color <- "purple"
active_color <- "#1f77b4"
recovered_color <- "forestgreen"
death_color <- "red"



######################

#####################
#####################
####################


cov<-leaflet(base_coviz_downl) %>% 
  ### On charge la carte avec un fond noir
  addTiles()%>% 
  ### On localise chaque pays par ses coordonnées géographiques et on dynamise le cumul du nombre de cas en fonction de la date
  addMinicharts(base_coviz_downl$new_long, base_coviz_downl$new_lat, chartdata = base_coviz_downl$Confirmed, width = 45, showLabels = TRUE,legend = TRUE, fillColor  = "red", time = base_coviz_downl$Report_Date_String)


```

RESUME {data-icon="fa-table"}
=====================================
Row 
-----------------------------------------------------------------------

### 

```{r}
articles1 = CasConfirmes()
valueBox(articles1,icon = "fa-user-plus",caption = "Nombre de cas Confirmés" ,color = "red")
```

### 

```{r}
articles2 = CasDecedes()
valueBox(articles2,icon = "fa-frown-open",caption = "Nombre de cas décédés" ,color = "black")
```

### 

```{r}
articles3 = casGueris()
valueBox(articles3,icon = "fa-user-times",caption = "Nombre de cas guéris" ,color = "green")
```

### 

```{r}
articles4 = casTraitement()
valueBox(articles4,icon = "fas fa-user-md",caption = "Nombre de cas sous traitement" ,color = "orange")
```

Row
-----------------------------------------------------------------------

### Carte   

```{r}
cov
```

EVOLUTION 
=====================================

```{r}
## 
base_pays_lim%>% filter(Report_Date_String >= "2020-03-13", Country_Region %in% c("Benin"))%>%accumulate_by(~absc)%>%
plotly::plot_ly( ) %>%
  plotly::add_trace(
    x = ~absc, 
    y = ~Confirmed,
    split = ~Country_Region,
    frame = ~frame, 
    type = 'scatter',
    mode = 'lines', 
    line = list(simplyfy = F),text = ~paste('</br> Date: ', Report_Date_String,
                                            '</br> Nombre: ', Confirmed,
                                            '</br> Pays: ', Country_Region
    )) %>%
plotly::add_trace(
    x = ~absc,
    y = ~Deaths,
    split = ~Country_Region,
    frame = ~frame, 
    type = 'scatter',
    mode = 'lines', 
    line = list(simplyfy = F),text = ~paste('</br> Date: ', Report_Date_String,
                                            '</br> Nombre: ', Deaths,
                                            '</br> Pays: ', Country_Region
  )) %>%
   plotly::add_annotations(
    x = 3.5,
    y = 1,
    text = paste("Premier cas confirmés"),
    xref = "x",
    yref = "y",
    arrowhead = 5,
    arrowhead = 3,
    arrowsize = 1,
    showarrow = TRUE,
    ax = -10,
    ay = -90
  ) %>%
   plotly::add_annotations(
    x = 4.1875,
    y = 1,
    text = paste("Premier décès"),
    xref = "x",
    yref = "y",
    arrowhead = 5,
    arrowhead = 3,
    arrowsize = 1,
    showarrow = TRUE,
    ax = -10,
    ay = -90
  ) %>%
   plotly::layout(
    title = "",
    yaxis = list(title = "Effectif cumulés des cas"),
    xaxis = list(title = "Date"),
    legend = list(x = 0.1, y = 0.9),
    hovermode = "compare")%>%
  animation_opts(
  frame = 100, 
  transition = 0, 
  redraw = FALSE
)%>%
  animation_slider(
  hide = T
) %>%
  animation_button(
  x = 1, xanchor = "right", y = 0, yanchor = "bottom"
)
```

CAS CONFIRMES
=====================================

```{r}
base_pays_lim%>% filter(Report_Date_String >= "2020-03-13", Country_Region %in% c("Benin", "Togo","Burkina Faso","Niger"))%>%accumulate_by(~absc)%>%
  plot_ly(
    x = ~absc, 
    y = ~Confirmed,
    split = ~Country_Region,
    frame = ~frame, 
    type = 'scatter',
    mode = 'lines', 
    line = list(simplyfy = F),text = ~paste('</br> Date: ', Report_Date_String,
                                            '</br> Nombre: ', Confirmed,
                                            '</br> Pays: ', Country_Region)
  ) %>% 
  layout(
  xaxis = list(
    title = "Mois",
    zeroline = F,
    dtick = 1
  ),
  yaxis = list(
    title = "Cas confirmés",
    zeroline = F
  )
) %>%
  animation_opts(
  frame = 100, 
  transition = 0, 
  redraw = FALSE
)%>%
  animation_slider(
  hide = T
) %>%
  animation_button(
  x = 1, xanchor = "right", y = 0, yanchor = "bottom"
)%>%
plotly::add_annotations(
    x = 3.40625,
    y = 1,
    text = paste("1er cas Burkina"),
    xref = "x",
    yref = "y",
    arrowhead = 5,
    arrowhead = 3,
    arrowsize = 1,
    showarrow = TRUE,
    ax = -50,
    ay = -50
  ) %>%
  plotly::add_annotations(
    x = 3.65625,
    y = 1,
    text = paste("1er cas Niger"),
    xref = "x",
    yref = "y",
    arrowhead = 5,
    arrowhead = 3,
    arrowsize = 1,
    showarrow = TRUE,
    ax = -10,
    ay = -90
  ) %>%
  plotly::add_annotations(
    x = 3.5,
    y = 1,
    text = paste("1er cas Togo"),
    xref = "x",
    yref = "y",
    arrowhead = 5,
    arrowhead = 3,
    arrowsize = 1,
    showarrow = TRUE,
    ax = -30,
    ay = -70
  ) %>%
  plotly::add_annotations(
    x = 3.5,
    y = 1,
    text = paste("1er cas Bénin"),
    xref = "x",
    yref = "y",
    arrowhead = 5,
    arrowhead = 3,
    arrowsize = 1,
    showarrow = TRUE,
    ax = -80,
    ay = -20
  )
```

DECES
=====================================

```{r}

base_pays_lim%>% filter(Report_Date_String >= "2020-03-13", Country_Region %in% c("Benin", "Togo","Burkina Faso","Niger"))%>%accumulate_by(~absc)%>%
  plot_ly(
    x = ~absc, 
    y = ~Deaths,
    split = ~Country_Region,
    frame = ~frame, 
    type = 'scatter',
    mode = 'lines', 
    line = list(simplyfy = F),text = ~paste('</br> Date: ', Report_Date_String,
                                            '</br> Nombre: ', Deaths,
                                            '</br> Pays: ', Country_Region)
  ) %>% 
  layout(
    xaxis = list(
      title = "Mois",
      zeroline = F,
      dtick = 1
    ),
    yaxis = list(
      title = "Cas décédés",
      zeroline = F
    )
  ) %>%
  animation_opts(
    frame = 100, 
    transition = 0, 
    redraw = FALSE
  )%>%
  animation_slider(
    hide = T
  ) %>%
  animation_button(
    x = 1, xanchor = "right", y = 0, yanchor = "bottom"
  )%>%
  plotly::add_annotations(
    x = as.Date("2020-03-18"),
    y = 1,
    text = paste("1er décès Burkina"),
    xref = "x",
    yref = "y",
    arrowhead = 5,
    arrowhead = 3,
    arrowsize = 1,
    showarrow = TRUE,
    ax = -50,
    ay = -50
  ) %>%
  plotly::add_annotations(
    x = 3.78125,
    y = 1,
    text = paste("1er décès Niger"),
    xref = "x",
    yref = "y",
    arrowhead = 5,
    arrowhead = 3,
    arrowsize = 1,
    showarrow = TRUE,
    ax = -10,
    ay = -90
  ) %>%
  plotly::add_annotations(
    x = 3.84375,
    y = 1,
    text = paste("1er décès Togo"),
    xref = "x",
    yref = "y",
    arrowhead = 5,
    arrowhead = 3,
    arrowsize = 1,
    showarrow = TRUE,
    ax = -30,
    ay = -70
  ) %>%
  plotly::add_annotations(
    x = 4.1875,
    y = 1,
    text = paste("1er cas Bénin"),
    xref = "x",
    yref = "y",
    arrowhead = 5,
    arrowhead = 3,
    arrowsize = 1,
    showarrow = TRUE,
    ax = -80,
    ay = -20
  )
```