---
title: "Evolution de la COVID19"
author: Rethis GANSEY
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readxl)
library(readr)
library(ggplot2)
library(animation)
library(gganimate)
library(leaflet)
library(leaflet.minicharts)
library(dplyr)
library(tidyverse)
library(dygraphs)
library(plotly)

# Chargement de la base de données
base_coviz<-read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/web-data/data/cases_country.csv")
base1<-base_coviz[which(base_coviz$Country_Region=="Benin" & base_coviz$Confirmed>0),]
indic1<-base1$Confirmed
indic2<-base1$Deaths
indic3<-base1$Recovered
indic4<-base1$Active

# these computing functions are only toy examples
CasConfirmes = function(...) return(indic1)
CasDecedes = function(...) return(indic2)
casGueris = function(...) return(indic3)
casTraitement = function(...) return(indic4)


base_coviz_downl<-read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/web-data/data/cases_time.csv")
base_coviz_downl$new_lat<-base_coviz$Lat[match(base_coviz_downl$Country_Region,base_coviz$Country_Region)]
base_coviz_downl$new_long<-base_coviz$Long_[match(base_coviz_downl$Country_Region,base_coviz$Country_Region)]
base2<-base_coviz_downl[which(base_coviz_downl$Country_Region=="Benin" & base_coviz_downl$Confirmed>0),]

graph_confirm1<-ggplot(base2, aes(Report_Date_String, Confirmed))+geom_line(color="#FC4E07", size=1)+ scale_color_viridis_d()+labs(title="Evolution du nombre de cas confirmés \n de la Covid-19 au Bénin", x="Date", y="Effectif", caption = "Made by Rethis Gansey")+theme(legend.position = "top", plot.title = element_text(color = "red", size = 14, face = "bold", hjust = 0.5), axis.title.x = element_text(color = "blue", size = 12, face="bold"), axis.title.y= element_text(color = "blue", size= 12, face="bold"))

graph_confirm2<-ggplot(base2, aes(Report_Date_String, Deaths))+geom_line(color="#FC4E07", size=1)+ scale_color_viridis_d()+labs(title="Evolution du nombre de cas décédés \n de la Covid-19 au Bénin", x="Date", y="Effectif", caption = "Made by Rethis Gansey")+theme(legend.position = "top", plot.title = element_text(color = "red", size = 14, face = "bold", hjust = 0.5), axis.title.x = element_text(color = "blue", size = 12, face="bold"), axis.title.y= element_text(color = "blue", size= 12, face="bold"))



cov<-leaflet(base_coviz_downl) %>% 
  ### On charge la carte avec un fond noir
  addTiles("http://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png",
                                              attribution = paste(                                                              
                                                "&copy; <a href=\"http://openstreetmap.org\">OpenStreetMap</a> contributors",   
                                                "&copy; <a href=\"http://cartodb.com/attributions\">CartoDB</a>"               
                                              ))%>% 
  ### On localise chaque pays par ses coordonnées géographiques et on dynamise le cumul du nombre de cas en fonction de la date
  addMinicharts(base_coviz_downl$new_long, base_coviz_downl$new_lat, chartdata = base_coviz_downl$Confirmed*0.001, width = 45, showLabels = TRUE,legend = TRUE, fillColor  = "red", time = base_coviz_downl$Report_Date_String)


```

RESUME {data-icon="fa-table"}
=====================================
Row 
-----------------------------------------------------------------------

### 

```{r}
articles1 = CasConfirmes()
valueBox(articles1,icon = "fa-user-plus",caption = "Nombre de cas Confirmés" ,color = "red")
```

### 

```{r}
articles2 = CasDecedes()
valueBox(articles2,icon = "fa-frown-open",caption = "Nombre de cas décédés" ,color = "black")
```

### 

```{r}
articles3 = casGueris()
valueBox(articles3,icon = "fa-user-times",caption = "Nombre de cas guéris" ,color = "green")
```

### 

```{r}
articles4 = casTraitement()
valueBox(articles4,icon = "fas fa-user-md",caption = "Nombre de cas sous traitement" ,color = "orange")
```

Row
-----------------------------------------------------------------------
### Cas confirmés  {data-width=310}

```{r}
ggplotly(graph_confirm1)
```

### Carte   

```{r}
cov
```

Courbes {data-icon="fa-signal"}
=====================================

Row
-----------------------------------------------------------------------
### Cas confirmés    

```{r}
ggplotly(graph_confirm1)
```
Row
-----------------------------------------------------------------------
### Cas décédés    

```{r}
ggplotly(graph_confirm2)
```
